"use client";

import React, { useState } from 'react';

export default function TypesOfDisasters() {
  const [activeGuide, setActiveGuide] = useState(null);

  const disasters = [
    {
      id: 1,
      title: 'Earthquakes',
      icon: 'earthquake',
      color: 'from-orange-400 to-red-500',
      description: 'Sudden shaking of the ground, sometimes causing massive destruction. Generated by seismic waves from tectonic plate movement.',
      safety: ['Drop, Cover, and Hold On', 'Stay away from glass and windows', 'If outside, move to an open area', 'Check for injuries and provide first aid', 'Be prepared for aftershocks']
    },
    {
      id: 2,
      title: 'Floods',
      icon: 'water_drop',
      color: 'from-blue-400 to-blue-600',
      description: 'An overflow of water that submerges land that is usually dry. The most common and widespread natural disaster worldwide.',
      safety: ['Evacuate to higher ground immediately', 'Do not walk through moving water', 'Do not drive into flooded areas', 'Disconnect electrical equipment', 'Monitor official emergency broadcasts']
    },
    {
      id: 3,
      title: 'Hurricanes',
      icon: 'cyclone',
      color: 'from-teal-400 to-cyan-600',
      description: 'Rapidly rotating storm system characterized by a low-pressure center, strong winds exceeding 119 km/h, and heavy rain.',
      safety: ['Board up windows and secure loose items', 'Follow mandatory evacuation orders', 'Stay indoors away from windows', 'Prepare emergency supply kit', 'Know your evacuation route in advance']
    },
    {
      id: 4,
      title: 'Wildfires',
      icon: 'local_fire_department',
      color: 'from-amber-400 to-orange-600',
      description: 'Uncontrolled fires that spread rapidly through vegetation. Often caused by drought conditions, lightning, or human activity.',
      safety: ['Create a defensible space around your home', 'Have an evacuation plan ready', 'Close all windows and doors', 'Wear protective clothing if evacuating', 'Monitor air quality advisories']
    },
    {
      id: 5,
      title: 'Tsunamis',
      icon: 'tsunami',
      color: 'from-indigo-400 to-purple-600',
      description: 'A series of ocean waves caused by large-scale disturbance of the ocean floor, typically from earthquakes or underwater volcanic eruptions.',
      safety: ['Move immediately to higher ground', 'Do not go to the shore to watch', 'Follow official evacuation routes', 'Stay away until authorities declare it safe', 'Be aware: waves may continue for hours']
    },
    {
      id: 6,
      title: 'Droughts',
      icon: 'wb_sunny',
      color: 'from-yellow-400 to-amber-600',
      description: 'Extended period of abnormally low rainfall leading to water shortage. Can cause devastating impacts on agriculture, water supply, and ecosystems.',
      safety: ['Conserve water in daily activities', 'Store emergency water supplies', 'Follow local water restrictions', 'Protect vegetation and reduce fire risk', 'Monitor government drought advisories']
    }
  ];

  return (
    <main id="main-content" className="max-w-7xl mx-auto px-8 py-20 min-h-screen">
      <div className="mb-16 text-center max-w-3xl mx-auto">
        <h1 className="text-5xl font-black text-gray-900 tracking-tight mb-6">
          Disaster Reference Guide
        </h1>
        <p className="text-lg text-gray-500 font-medium">
          Comprehensive safety protocols and guidelines for major natural disasters. Click on any disaster module below to view critical survival protocols.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {disasters.map((disaster) => (
          <div key={disaster.id} className="relative group">
            <div className={`p-8 rounded-3xl bg-white border border-gray-200 shadow-sm transition-all duration-300 hover:shadow-2xl hover:border-transparent ${activeGuide === disaster.id ? 'ring-4 ring-blue-500/20' : ''}`}>
              
              <div className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${disaster.color} flex items-center justify-center mb-6 shadow-inner`}>
                 <span className="material-symbols-outlined text-white text-3xl">{disaster.icon}</span>
              </div>
              
              <h2 className="text-2xl font-bold text-gray-900 mb-3">{disaster.title}</h2>
              <p className="text-gray-500 mb-8 leading-relaxed line-clamp-3">
                {disaster.description}
              </p>
              
              <button 
                onClick={() => setActiveGuide(activeGuide === disaster.id ? null : disaster.id)}
                className="w-full py-4 text-center font-bold text-gray-700 bg-gray-50 hover:bg-gray-100 rounded-xl transition-colors active:scale-95"
                aria-expanded={activeGuide === disaster.id}
                aria-controls={`safety-${disaster.id}`}
              >
                {activeGuide === disaster.id ? 'Close Guidelines' : 'View Safety Protocols'}
              </button>

              {/* Extended State for Safety Rules */}
              {activeGuide === disaster.id && (
                <div 
                  id={`safety-${disaster.id}`}
                  className="absolute inset-0 z-10 bg-white/95 backdrop-blur-md rounded-3xl p-8 border hover:border-gray-300 shadow-2xl flex flex-col justify-center animate-in fade-in zoom-in duration-200"
                  role="region"
                  aria-label={`${disaster.title} safety protocols`}
                >
                  <h3 className="text-xl font-bold text-gray-900 mb-4">{disaster.title} Protocols</h3>
                  <ul className="space-y-4">
                    {disaster.safety.map((rule, idx) => (
                       <li key={idx} className="flex items-start gap-3">
                         <span className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-xs font-bold mt-0.5">{idx + 1}</span>
                         <span className="text-gray-700 font-medium">{rule}</span>
                       </li>
                    ))}
                  </ul>
                  <button 
                    onClick={() => setActiveGuide(null)}
                    className="mt-8 text-sm font-bold text-gray-400 hover:text-gray-600 uppercase tracking-widest text-center"
                    aria-label={`Close ${disaster.title} safety protocols`}
                  >
                    Close
                  </button>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
